"""
A Collatz sequence is generated by repeatedly applying the following rules to an integer and then to each resulting integer in turn:

If even: divide by 2.
If odd: multiply by 3, then add 1.
The Collatz algorithm has been tested and found to always reach 1 for all positive integers.

Create a function that, when given two positive integers a b, returns the string "a" if integer a took fewer steps to reach 1 than b when passed through the Collatz sequence, or "b" if integer b took fewer steps to reach 1 than a.

Examples
collatz(10, 15) ➞ "a"
# Because 10.0 - 5.0 - 16.0 - 8.0 - 4.0 - 2.0 - 1.0: 6 steps
# 15.0 - 46.0 - 23.0 - 70.0 - 35.0 - 106.0 - 53.0 - 160.0 - 80.0 - 40.0 - 20.0 - 10.0 - 5.0 - 16.0 - 8.0 - 4.0 - 2.0 - 1.0: 17 steps

collatz(13, 16) ➞ "b"

collatz(53782, 72534) ➞ "b"
"""

# Using 2n iterations

def collatz(n1, n2):
    n1_current = n1
    n1_count = 0
    n2_current = n2
    n2_count = 0
    while n1_current != 1:
        if n1_current % 2 == 0:
            n1_current = n1_current / 2
            n1_count += 1
        else:
            n1_current = (n1_current * 3) + 1
            n1_count += 1
    while n2_current != 1:
        if n2_current % 2 == 0:
            n2_current = n2_current / 2
            n2_count += 1
        else:
            n2_current = (n2_current * 3) + 1
            n2_count += 1
    if n1_count < n2_count:
        return "a"
    else:
        return "b"

# Using n iterations

# def collatz(n1, n2):
#     n1_current = n1
#     n2_current = n2
#     while n1_current != 1 and n2_current != 1:
#         if n1_current == 1:
#             return "a"
#         elif n2_current == 1:
#             return "b"
#         else:
#             if n1_current % 2 == 0:
#                 n1_current = n1_current / 2
#             else:
#                 n1_current = (n1_current * 3) + 1
#
#             if n2_current % 2 == 0:
#                 n2_current = n2_current / 2
#             else:
#                 n2_current = (n2_current * 3) + 1


print(collatz(10, 15))
print(collatz(13, 16))
print(collatz(53782, 72534))
