"""
You are given two strings s and t. String t is generated by randomly shuffling string s and then adding one more letter at a random position. Return the letter that was added to t.

Examples
find_the_difference("abcd", "abcde") ➞ "e"

find_the_difference("", "y") ➞ "y"

find_the_difference("ae", "aea") ➞ "a"

From: https://edabit.com/challenge/bm6sQhgQ7KESi6gff
"""

def find_the_difference(s, t):
    histogram_s = {}
    histogram_t = {}
    for letter in s:
        if letter not in histogram_s:
            histogram_s[letter] = 1
        else:
            histogram_s[letter] += 1
    for letter in t:
        if letter not in histogram_t:
            histogram_t[letter] = 1
        else:
            histogram_t[letter] += 1
    for key in histogram_t:
        if key not in histogram_s:
            return key
        if histogram_t[key] != histogram_s[key]:
            return key
    return "Error"

print(find_the_difference("abcd", "abcde"))
print(find_the_difference("", "y"))
print(find_the_difference("ae", "aea"))
